import type { LocationOption, PublicCampaign } from "@/lib/types/domain";

export const demoLocations: LocationOption[] = [
  ["Jaén", "jaen"],
  ["Bellavista", "bellavista"],
  ["Chontalí", "chontali"],
  ["Colasay", "colasay"],
  ["Huabal", "huabal"],
  ["Las Pirias", "las-pirias"],
  ["Pomahuaca", "pomahuaca"],
  ["Pucará", "pucara"],
  ["Sallique", "sallique"],
  ["San Felipe", "san-felipe"],
  ["San José del Alto", "san-jose-del-alto"],
  ["Santa Rosa", "santa-rosa"],
].map(([district, slug], index) => ({
  id: `00000000-0000-4000-8000-${String(index + 1).padStart(12, "0")}`,
  province: "Jaén",
  district,
  slug,
}));

export const demoCampaigns: PublicCampaign[] = [
  {
    id: "10000000-0000-4000-8000-000000000001",
    slug: "cosecha-finca-santa-rosa",
    title: "Cosecha de café maduro",
    farmName: "Finca Santa Rosa",
    district: "Chontalí",
    province: "Jaén",
    startDate: "2026-08-12",
    endDate: "2026-09-20",
    workType: "harvest",
    paymentMode: "per_unit",
    paymentAmount: 18,
    paymentUnitLabel: "por arroba",
    workersNeeded: 8,
    includesFood: true,
    includesLodging: true,
    transportProvided: false,
    description: "Buscamos personas con experiencia en cosecha selectiva de café maduro. La cuadrilla trabaja por la mañana y por la tarde, con descanso al mediodía.",
    locationReference: "A 30 minutos de Chontalí, por la ruta a La Palma.",
    safetyNote: "Trae botas y ropa para lluvia. La finca brinda herramientas, un punto de encuentro y una charla antes de iniciar.",
    rating: 4.8,
    completedCampaigns: 7,
    ratingComments: ["Las condiciones y el pago coincidieron con lo publicado."],
    status: "published",
    isDemo: true,
  },
  {
    id: "10000000-0000-4000-8000-000000000002",
    slug: "mantenimiento-el-mirador",
    title: "Mantenimiento de cafetal",
    farmName: "Finca El Mirador",
    district: "Bellavista",
    province: "Jaén",
    startDate: "2026-08-18",
    endDate: "2026-08-30",
    workType: "maintenance",
    paymentMode: "per_day",
    paymentAmount: 55,
    paymentUnitLabel: "por jornada",
    workersNeeded: 4,
    includesFood: true,
    includesLodging: false,
    transportProvided: false,
    description: "Campaña de deshierbe y abonado. Recomendada para personas que viven en Bellavista o pueden movilizarse por sus propios medios.",
    locationReference: "A 15 minutos de Bellavista, cerca del desvío San Juan.",
    safetyNote: "Se trabaja con herramientas de la finca. La jornada empieza con indicaciones sobre el terreno y el manejo de insumos.",
    rating: 4.6,
    completedCampaigns: 4,
    ratingComments: ["La finca explicó bien las tareas antes de comenzar."],
    status: "published",
    isDemo: true,
  },
  {
    id: "10000000-0000-4000-8000-000000000003",
    slug: "postcosecha-la-esperanza",
    title: "Apoyo en postcosecha",
    farmName: "Finca La Esperanza",
    district: "San José del Alto",
    province: "Jaén",
    startDate: "2026-08-25",
    endDate: "2026-09-15",
    workType: "postharvest",
    paymentMode: "per_week",
    paymentAmount: 360,
    paymentUnitLabel: "por semana",
    workersNeeded: 3,
    includesFood: true,
    includesLodging: true,
    transportProvided: true,
    description: "Apoyo en selección, lavado y secado de café. Se valora experiencia en beneficio húmedo, aunque la finca brinda una inducción inicial.",
    locationReference: "A 40 minutos de San José del Alto, con movilidad coordinada desde el distrito.",
    safetyNote: "La campaña incluye inducción de seguridad, implementos básicos y alojamiento compartido para la cuadrilla.",
    rating: 4.9,
    completedCampaigns: 9,
    ratingComments: ["Buena coordinación para la movilidad y el alojamiento."],
    status: "published",
    isDemo: true,
  },
];
