import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteHeader } from "@/components/site-header";
import { campaigns, getCampaign } from "@/lib/campaigns";

export function generateStaticParams() { return campaigns.map(({ slug }) => ({ slug })); }
export function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { return params.then(({ slug }) => { const campaign = getCampaign(slug); return { title: campaign ? `${campaign.title} — ${campaign.farm}` : "Campaña no encontrada" }; }); }

export default async function CampaignDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const campaign = getCampaign((await params).slug);
  if (!campaign) notFound();
  return <><SiteHeader /><main className="mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:px-8"><Link className="text-sm font-semibold text-[#28533b] underline underline-offset-4" href="/campanas">← Volver a campañas</Link><div className="mt-6 grid gap-8 lg:grid-cols-[1fr_19rem]"><article><p className="text-sm font-semibold tracking-wide text-[#74502d]">{campaign.workType.toUpperCase()} · {campaign.province.toUpperCase()}</p><h1 className="mt-2 text-4xl font-semibold tracking-tight text-[#173624]">{campaign.title}</h1><p className="mt-2 text-lg text-[#526257]">{campaign.farm} · {campaign.district}</p><div className="mt-7 rounded-2xl border border-[#dcd7c9] bg-[#fbfaf5] p-5"><h2 className="text-lg font-semibold text-[#173624]">Sobre el trabajo</h2><p className="mt-3 leading-7 text-[#405246]">{campaign.description}</p></div><div className="mt-5 grid gap-5 sm:grid-cols-2"><section><h2 className="font-semibold text-[#173624]">Ubicación</h2><p className="mt-2 leading-7 text-[#526257]">{campaign.locationReference}</p></section><section><h2 className="font-semibold text-[#173624]">Seguridad y normas</h2><p className="mt-2 leading-7 text-[#526257]">{campaign.safetyNote}</p></section></div></article><aside className="h-fit rounded-2xl border border-[#cbd8be] bg-[#eef4e6] p-5"><p className="text-sm font-semibold text-[#28533b]">CONDICIONES CLARAS</p><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-[#66756c]">Fechas estimadas</dt><dd className="mt-0.5 font-semibold text-[#173624]">{campaign.startDate} — {campaign.endDate}</dd></div><div><dt className="text-[#66756c]">Pago</dt><dd className="mt-0.5 font-semibold text-[#173624]">{campaign.paymentDetail} ({campaign.payment.toLowerCase()})</dd></div><div><dt className="text-[#66756c]">Beneficios</dt><dd className="mt-0.5 font-semibold text-[#173624]">{campaign.includesFood ? "Comida incluida" : "Sin comida"} · {campaign.includesLodging ? "Alojamiento incluido" : "Sin alojamiento"}</dd></div><div><dt className="text-[#66756c]">Cupos</dt><dd className="mt-0.5 font-semibold text-[#173624]">{campaign.workersNeeded} trabajadores</dd></div></dl><Link href="/registro?rol=worker" className="mt-7 inline-flex min-h-12 w-full items-center justify-center rounded-xl bg-[#28533b] px-4 font-semibold text-white transition hover:bg-[#173624]">Me interesa</Link><p className="mt-3 text-center text-xs leading-5 text-[#526257]">Crearás tu perfil antes de postular. El contacto se comparte solo después de una aceptación.</p></aside></div></main></>;
}
